[package]
name = "pprof"
version = "0.3.12"
authors = ["Yang Keao <keao.yang@yahoo.com>"]
edition = "2018"
license = "Apache-2.0"
description = "An internal perf tools for rust programs."
repository = "https://github.com/tikv/pprof-rs"
documentation = "https://docs.rs/pprof/"
readme = "README.md"

[features]
flamegraph = ["inferno"]
protobuf = ["prost", "prost-derive", "prost-build"]

[dependencies]
backtrace = "0.3"
lazy_static = "1.4.0"
libc = "0.2"
log = "0.4"
nix = "0.16.0"
rustc-demangle = "0.1.16"
spin = "0.5.2"
tempfile = "3.1.0"
thiserror = "1.0"

inferno = { version = "0.9.0", default-features = false, features = ["nameattr"], optional = true }
prost = { version = "0.6", optional = true }
prost-derive = { version = "0.6", optional = true }

[dev-dependencies]
rand = "0.7.2"

[build-dependencies]
prost-build = { version = "0.6", optional = true }

[[example]]
name = "flamegraph"
required-features = ["flamegraph"]

[[example]]
name = "profile_proto"
required-features = ["protobuf"]

[[example]]
name = "multithread_flamegraph"
required-features = ["flamegraph"]

[package.metadata.docs.rs]
all-features = true
