[package]
name = "pprof"
version = "0.3.3"
authors = ["Yang Keao <keao.yang@yahoo.com>"]
edition = "2018"
license = "Apache-2.0"
description = "An internal perf tools for rust programs."
repository = "https://github.com/YangKeao/rsperftools"

[features]
flamegraph = ["inferno"]

[dependencies]
backtrace = "0.3"
lazy_static = "1.4.0"
nix = "0.15.0"
quick-error = "1.2.2"
inferno = { version = "0.9.0", optional = true }
log = "0.4"
spin = "0.5.2"
rustc-demangle = "0.1.16"
tempfile = "3.1.0"
memmap = "0.7.0"
libc = "0.2"

[[example]]
name = "flamegraph"
required-features = ["flamegraph"]

[[example]]
name = "multithread_flamegraph"
required-features = ["flamegraph"]
